# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0006_auto_20170621_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=38)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
