# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0007_auto_20170621_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=b'', max_length=38),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=b'', max_length=38),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=b'', max_length=38),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=b'', max_length=38),
        ),
    ]
