# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0009_auto_20170622_0028'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
