# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0010_auto_20170624_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke', models.CharField(max_length=38)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='third_app.User')),
                ('userpoked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpoked', to='third_app.User')),
            ],
        ),
    ]
