# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0012_remove_poke_poke'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='', max_length=38),
        ),
    ]
