# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0015_poke_poke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poke',
            field=models.CharField(default='poked', max_length=38),
        ),
    ]
