# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0016_auto_20170628_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
