# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0019_auto_20170628_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poke',
        ),
    ]
