# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0020_auto_20170628_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='userpoked',
            new_name='poked',
        ),
        migrations.RenameField(
            model_name='poke',
            old_name='user',
            new_name='poker',
        ),
    ]
