# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0021_auto_20170629_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='pokes',
            field=models.IntegerField(default=1),
        ),
    ]
