# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0024_auto_20170629_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='quote1',
        ),
    ]
