# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0025_auto_20170629_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='third_app.Quote'),
        ),
    ]
